set_false_path -from [get_clocks clk_pl_0] -to [get_ports LED2_N_PWR_SYNC]

create_clock -period 8.000 -name SOM_CLK_1 -waveform {0.000 4.000} [get_ports {SOM_IN_CLK_P[1]}]
create_clock -period 8.000 -name SOM_CLK_0 -waveform {0.000 4.000} [get_ports {SOM_IN_CLK_P[0]}]
create_clock -period 4.000 -name TD_CLK -waveform {0.000 2.000} [get_ports FPGA_CLK250_TD_P]
create_clock -period 10.000 -name OSC_CLK -waveform {0.000 5.000} [get_ports CLNR_OSC_P]

# create_clock -period 8.000 -name {ADC_DCO[1]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[1]}]
# create_clock -period 8.000 -name {ADC_DCO[2]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[2]}]
# create_clock -period 8.000 -name {ADC_DCO[3]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[3]}]
# create_clock -period 8.000 -name {ADC_DCO[4]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[4]}]
# create_clock -period 8.000 -name {ADC_DCO[5]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[5]}]
# create_clock -period 8.000 -name {ADC_DCO[6]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[6]}]
# create_clock -period 8.000 -name {ADC_DCO[7]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[7]}]
# create_clock -period 8.000 -name {ADC_DCO[8]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[8]}]
# create_clock -period 8.000 -name {ADC_DCO[9]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[9]}]
# create_clock -period 8.000 -name {ADC_DCO[10]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[10]}]
# create_clock -period 8.000 -name {ADC_DCO[11]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[11]}]
# create_clock -period 8.000 -name {ADC_DCO[12]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[12]}]
# create_clock -period 8.000 -name {ADC_DCO[13]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[13]}]
# create_clock -period 8.000 -name {ADC_DCO[14]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[14]}]
# create_clock -period 8.000 -name {ADC_DCO[15]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[15]}]
# create_clock -period 8.000 -name {ADC_DCO[16]} -waveform {0.000 4.000} [get_ports {ADC_DCO_P[16]}]

# set_clock_groups -asynchronous -group clk_pl_0 -group SOM_CLK_0 -group SOM_CLK_1 -group TD_CLK -group OSC_CLK -group ADC_DCO[1] -group ADC_DCO[2] -group ADC_DCO[3] -group ADC_DCO[4] -group ADC_DCO[5] -group ADC_DCO[6] -group ADC_DCO[7] -group ADC_DCO[8] -group ADC_DCO[9] -group ADC_DCO[10] -group ADC_DCO[11] -group ADC_DCO[12] -group ADC_DCO[13] -group ADC_DCO[14] -group ADC_DCO[15] -group ADC_DCO[16]
set_clock_groups -asynchronous -group clk_pl_0 -group clk_pl_1 -group TD_CLK -group OSC_CLK


# set_false_path -from [get_ports LMK_STAT_HOLDOVER]
# set_false_path -from [get_ports LMK_STAT_LD]
# set_false_path -from [get_ports {SW1[*]}]
# set_false_path -to [get_ports {LED_DSP[*]}]
# set_false_path -to [get_ports LMK_UWIRE_CLK]
# set_false_path -to [get_ports LMK_UWIRE_DATA]
# set_false_path -to [get_ports LMK_UWIRE_LE]

set_false_path -from [get_ports {SW1[5]}] -to [get_ports LMK_STAT_CLKin1]
set_false_path -from [get_ports {SW1[6]}] -to [get_ports LMK_STAT_CLKin0]
set_false_path  -to [get_ports LMK_STAT_HOLDOVER]
set_false_path -to [get_ports {LED_DSP[*]}]

set_output_delay -clock [get_clocks OSC_CLK] -min -add_delay 0.000 [get_ports LMK_UWIRE_CLK]
set_output_delay -clock [get_clocks OSC_CLK] -max -add_delay 0.200 [get_ports LMK_UWIRE_CLK]
set_output_delay -clock [get_clocks OSC_CLK] -min -add_delay 0.000 [get_ports LMK_UWIRE_DATA]
set_output_delay -clock [get_clocks OSC_CLK] -max -add_delay 0.200 [get_ports LMK_UWIRE_DATA]
set_output_delay -clock [get_clocks OSC_CLK] -min -add_delay 0.000 [get_ports LMK_UWIRE_LE]
set_output_delay -clock [get_clocks OSC_CLK] -max -add_delay 0.200 [get_ports LMK_UWIRE_LE]

set_false_path -from [get_clocks OSC_CLK] -to [get_clocks clk_adc_mmcm_adc]
set_false_path -from [get_clocks -of_objects [get_pins clock_subsystem/adc_mmcm/inst/mmcme4_adv_inst/CLKOUT1]] -to [get_clocks OSC_CLK]
set_false_path -from [get_clocks -of_objects [get_pins clock_subsystem/adc_mmcm/inst/mmcme4_adv_inst/CLKOUT1]] -to [get_clocks TD_CLK]




set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[36]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[0]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA_VALID[5]}]
set_property MARK_DEBUG true [get_nets bd/COM5501_0/MAC_TX_EOF]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[7]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[4]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA_VALID[1]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[53]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[57]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[41]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[61]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[25]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[45]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[49]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[37]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[5]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[8]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[29]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[33]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[21]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[32]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[28]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[40]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[16]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[12]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[24]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[20]}]
set_property MARK_DEBUG true [get_nets bd/COM5501_0/MAC_RX_EOF]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[13]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[17]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[1]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA_VALID[0]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA_VALID[7]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[60]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA_VALID[4]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[48]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[44]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[56]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[52]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA_VALID[4]}]
set_property MARK_DEBUG true [get_nets bd/COM5501_0/SYNC_RESET]
set_property MARK_DEBUG true [get_nets bd/COM5501_0/MAC_TX_CTS]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[4]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[12]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[16]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[7]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA_VALID[0]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[60]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[52]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[56]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[36]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[44]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[48]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[40]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[20]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[28]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[32]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[24]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[3]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA_VALID[7]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[9]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[11]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[15]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[27]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[39]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[35]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[31]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[23]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[19]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[63]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[59]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA_VALID[3]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[47]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[43]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[55]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[51]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[18]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[10]}]
set_property MARK_DEBUG true [get_nets bd/COM5501_0/MAC_RX_SOF]
set_property MARK_DEBUG true [get_nets bd/COM5501_0/RESET_N]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[6]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[55]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[59]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[9]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[15]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[19]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[11]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[31]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[35]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[23]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[27]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[47]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[51]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[39]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[43]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[63]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA_VALID[3]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[30]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[42]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[38]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[14]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[26]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[22]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[2]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[3]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA_VALID[2]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[62]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA_VALID[6]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[50]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[58]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[54]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[46]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[34]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[1]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[0]}]
set_property MARK_DEBUG true [get_nets bd/COM5501_0/MAC_RX_FRAME_VALID]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[6]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[14]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[18]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[10]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[30]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[34]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[22]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[26]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[46]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[50]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[38]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[42]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[62]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[2]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA_VALID[2]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[5]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[54]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA[58]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[8]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_RX_DATA_VALID[6]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[13]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[17]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[41]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[37]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[29]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[33]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[25]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[21]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA_VALID[1]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[61]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[49]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[57]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[53]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA[45]}]
set_property MARK_DEBUG true [get_nets {bd/COM5501_0/MAC_TX_DATA_VALID[5]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[40]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[6]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data_valid[0]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[0]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[24]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[16]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[56]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[48]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[32]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[7]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[32]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[40]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[16]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[24]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[0]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[7]}]
set_property MARK_DEBUG true [get_nets bd/tcp_udp_client_0/mac_tx_eof]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[14]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[54]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[62]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[38]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[46]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[22]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[30]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[39]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[63]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[5]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[37]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[13]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data_valid[6]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[55]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[47]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[31]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[15]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[23]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[47]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[9]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[31]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[39]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[15]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[23]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[9]}]
set_property MARK_DEBUG true [get_nets bd/tcp_udp_client_0/mac_tx_cts]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data_valid[6]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[61]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[53]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[45]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[21]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[29]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[30]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data_valid[5]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[46]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[54]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[38]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[14]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[22]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[46]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[6]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[30]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[38]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[14]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[22]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[6]}]
set_property MARK_DEBUG true [get_nets bd/tcp_udp_client_0/mac_rx_sof]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[12]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[62]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[4]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data_valid[5]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[52]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[60]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[36]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[44]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[20]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[28]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[53]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data_valid[4]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data_valid[4]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[45]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[29]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[37]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[13]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[21]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[45]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[5]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[29]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[37]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[13]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[21]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[5]}]
set_property MARK_DEBUG true [get_nets bd/tcp_udp_client_0/mac_rx_frame_valid]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[11]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[61]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[3]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[59]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[51]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[35]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[43]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[19]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[27]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[36]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[60]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data_valid[3]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[44]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[20]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[12]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[28]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[52]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[44]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[4]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[28]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[36]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[12]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[20]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[4]}]
set_property MARK_DEBUG true [get_nets bd/tcp_udp_client_0/mac_rx_eof]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[10]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data_valid[3]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[50]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[58]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[34]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[42]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[18]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[26]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[2]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[35]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data_valid[2]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[59]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[11]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[27]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[51]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[43]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[3]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[19]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[43]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[27]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[35]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[11]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[19]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[3]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[8]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data_valid[2]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[57]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[49]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[33]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[41]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[17]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[25]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[1]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[50]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[0]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data_valid[1]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[42]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[26]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[34]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[18]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[42]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[10]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[2]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[26]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[34]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[10]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[18]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[2]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[58]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[7]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data_valid[1]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[48]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[56]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[32]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[40]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[16]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[24]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[49]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[15]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data_valid[0]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[41]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[25]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[33]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[8]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[17]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[41]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[1]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[25]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[33]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[8]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[17]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_addr[1]}]
set_property MARK_DEBUG true [get_nets bd/tcp_udp_client_0/sync_reset]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data[57]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[9]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[63]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data_valid[7]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[31]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[55]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[47]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[39]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_tx_data[23]}]
set_property MARK_DEBUG true [get_nets {bd/tcp_udp_client_0/mac_rx_data_valid[7]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clock_subsystem/adc_mmcm/inst/clk_adc]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 48 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {bd/tcp_udp_client_0/mac_addr[0]} {bd/tcp_udp_client_0/mac_addr[1]} {bd/tcp_udp_client_0/mac_addr[2]} {bd/tcp_udp_client_0/mac_addr[3]} {bd/tcp_udp_client_0/mac_addr[4]} {bd/tcp_udp_client_0/mac_addr[5]} {bd/tcp_udp_client_0/mac_addr[6]} {bd/tcp_udp_client_0/mac_addr[7]} {bd/tcp_udp_client_0/mac_addr[8]} {bd/tcp_udp_client_0/mac_addr[9]} {bd/tcp_udp_client_0/mac_addr[10]} {bd/tcp_udp_client_0/mac_addr[11]} {bd/tcp_udp_client_0/mac_addr[12]} {bd/tcp_udp_client_0/mac_addr[13]} {bd/tcp_udp_client_0/mac_addr[14]} {bd/tcp_udp_client_0/mac_addr[15]} {bd/tcp_udp_client_0/mac_addr[16]} {bd/tcp_udp_client_0/mac_addr[17]} {bd/tcp_udp_client_0/mac_addr[18]} {bd/tcp_udp_client_0/mac_addr[19]} {bd/tcp_udp_client_0/mac_addr[20]} {bd/tcp_udp_client_0/mac_addr[21]} {bd/tcp_udp_client_0/mac_addr[22]} {bd/tcp_udp_client_0/mac_addr[23]} {bd/tcp_udp_client_0/mac_addr[24]} {bd/tcp_udp_client_0/mac_addr[25]} {bd/tcp_udp_client_0/mac_addr[26]} {bd/tcp_udp_client_0/mac_addr[27]} {bd/tcp_udp_client_0/mac_addr[28]} {bd/tcp_udp_client_0/mac_addr[29]} {bd/tcp_udp_client_0/mac_addr[30]} {bd/tcp_udp_client_0/mac_addr[31]} {bd/tcp_udp_client_0/mac_addr[32]} {bd/tcp_udp_client_0/mac_addr[33]} {bd/tcp_udp_client_0/mac_addr[34]} {bd/tcp_udp_client_0/mac_addr[35]} {bd/tcp_udp_client_0/mac_addr[36]} {bd/tcp_udp_client_0/mac_addr[37]} {bd/tcp_udp_client_0/mac_addr[38]} {bd/tcp_udp_client_0/mac_addr[39]} {bd/tcp_udp_client_0/mac_addr[40]} {bd/tcp_udp_client_0/mac_addr[41]} {bd/tcp_udp_client_0/mac_addr[42]} {bd/tcp_udp_client_0/mac_addr[43]} {bd/tcp_udp_client_0/mac_addr[44]} {bd/tcp_udp_client_0/mac_addr[45]} {bd/tcp_udp_client_0/mac_addr[46]} {bd/tcp_udp_client_0/mac_addr[47]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list bd/xxv_ethernet_0/inst/i_core_gtwiz_userclk_tx_inst_0/MGT_B228_RX0_N]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 64 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {bd/COM5501_0/MAC_RX_DATA[0]} {bd/COM5501_0/MAC_RX_DATA[1]} {bd/COM5501_0/MAC_RX_DATA[2]} {bd/COM5501_0/MAC_RX_DATA[3]} {bd/COM5501_0/MAC_RX_DATA[4]} {bd/COM5501_0/MAC_RX_DATA[5]} {bd/COM5501_0/MAC_RX_DATA[6]} {bd/COM5501_0/MAC_RX_DATA[7]} {bd/COM5501_0/MAC_RX_DATA[8]} {bd/COM5501_0/MAC_RX_DATA[9]} {bd/COM5501_0/MAC_RX_DATA[10]} {bd/COM5501_0/MAC_RX_DATA[11]} {bd/COM5501_0/MAC_RX_DATA[12]} {bd/COM5501_0/MAC_RX_DATA[13]} {bd/COM5501_0/MAC_RX_DATA[14]} {bd/COM5501_0/MAC_RX_DATA[15]} {bd/COM5501_0/MAC_RX_DATA[16]} {bd/COM5501_0/MAC_RX_DATA[17]} {bd/COM5501_0/MAC_RX_DATA[18]} {bd/COM5501_0/MAC_RX_DATA[19]} {bd/COM5501_0/MAC_RX_DATA[20]} {bd/COM5501_0/MAC_RX_DATA[21]} {bd/COM5501_0/MAC_RX_DATA[22]} {bd/COM5501_0/MAC_RX_DATA[23]} {bd/COM5501_0/MAC_RX_DATA[24]} {bd/COM5501_0/MAC_RX_DATA[25]} {bd/COM5501_0/MAC_RX_DATA[26]} {bd/COM5501_0/MAC_RX_DATA[27]} {bd/COM5501_0/MAC_RX_DATA[28]} {bd/COM5501_0/MAC_RX_DATA[29]} {bd/COM5501_0/MAC_RX_DATA[30]} {bd/COM5501_0/MAC_RX_DATA[31]} {bd/COM5501_0/MAC_RX_DATA[32]} {bd/COM5501_0/MAC_RX_DATA[33]} {bd/COM5501_0/MAC_RX_DATA[34]} {bd/COM5501_0/MAC_RX_DATA[35]} {bd/COM5501_0/MAC_RX_DATA[36]} {bd/COM5501_0/MAC_RX_DATA[37]} {bd/COM5501_0/MAC_RX_DATA[38]} {bd/COM5501_0/MAC_RX_DATA[39]} {bd/COM5501_0/MAC_RX_DATA[40]} {bd/COM5501_0/MAC_RX_DATA[41]} {bd/COM5501_0/MAC_RX_DATA[42]} {bd/COM5501_0/MAC_RX_DATA[43]} {bd/COM5501_0/MAC_RX_DATA[44]} {bd/COM5501_0/MAC_RX_DATA[45]} {bd/COM5501_0/MAC_RX_DATA[46]} {bd/COM5501_0/MAC_RX_DATA[47]} {bd/COM5501_0/MAC_RX_DATA[48]} {bd/COM5501_0/MAC_RX_DATA[49]} {bd/COM5501_0/MAC_RX_DATA[50]} {bd/COM5501_0/MAC_RX_DATA[51]} {bd/COM5501_0/MAC_RX_DATA[52]} {bd/COM5501_0/MAC_RX_DATA[53]} {bd/COM5501_0/MAC_RX_DATA[54]} {bd/COM5501_0/MAC_RX_DATA[55]} {bd/COM5501_0/MAC_RX_DATA[56]} {bd/COM5501_0/MAC_RX_DATA[57]} {bd/COM5501_0/MAC_RX_DATA[58]} {bd/COM5501_0/MAC_RX_DATA[59]} {bd/COM5501_0/MAC_RX_DATA[60]} {bd/COM5501_0/MAC_RX_DATA[61]} {bd/COM5501_0/MAC_RX_DATA[62]} {bd/COM5501_0/MAC_RX_DATA[63]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 8 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {bd/COM5501_0/MAC_RX_DATA_VALID[0]} {bd/COM5501_0/MAC_RX_DATA_VALID[1]} {bd/COM5501_0/MAC_RX_DATA_VALID[2]} {bd/COM5501_0/MAC_RX_DATA_VALID[3]} {bd/COM5501_0/MAC_RX_DATA_VALID[4]} {bd/COM5501_0/MAC_RX_DATA_VALID[5]} {bd/COM5501_0/MAC_RX_DATA_VALID[6]} {bd/COM5501_0/MAC_RX_DATA_VALID[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 64 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {bd/COM5501_0/MAC_TX_DATA[0]} {bd/COM5501_0/MAC_TX_DATA[1]} {bd/COM5501_0/MAC_TX_DATA[2]} {bd/COM5501_0/MAC_TX_DATA[3]} {bd/COM5501_0/MAC_TX_DATA[4]} {bd/COM5501_0/MAC_TX_DATA[5]} {bd/COM5501_0/MAC_TX_DATA[6]} {bd/COM5501_0/MAC_TX_DATA[7]} {bd/COM5501_0/MAC_TX_DATA[8]} {bd/COM5501_0/MAC_TX_DATA[9]} {bd/COM5501_0/MAC_TX_DATA[10]} {bd/COM5501_0/MAC_TX_DATA[11]} {bd/COM5501_0/MAC_TX_DATA[12]} {bd/COM5501_0/MAC_TX_DATA[13]} {bd/COM5501_0/MAC_TX_DATA[14]} {bd/COM5501_0/MAC_TX_DATA[15]} {bd/COM5501_0/MAC_TX_DATA[16]} {bd/COM5501_0/MAC_TX_DATA[17]} {bd/COM5501_0/MAC_TX_DATA[18]} {bd/COM5501_0/MAC_TX_DATA[19]} {bd/COM5501_0/MAC_TX_DATA[20]} {bd/COM5501_0/MAC_TX_DATA[21]} {bd/COM5501_0/MAC_TX_DATA[22]} {bd/COM5501_0/MAC_TX_DATA[23]} {bd/COM5501_0/MAC_TX_DATA[24]} {bd/COM5501_0/MAC_TX_DATA[25]} {bd/COM5501_0/MAC_TX_DATA[26]} {bd/COM5501_0/MAC_TX_DATA[27]} {bd/COM5501_0/MAC_TX_DATA[28]} {bd/COM5501_0/MAC_TX_DATA[29]} {bd/COM5501_0/MAC_TX_DATA[30]} {bd/COM5501_0/MAC_TX_DATA[31]} {bd/COM5501_0/MAC_TX_DATA[32]} {bd/COM5501_0/MAC_TX_DATA[33]} {bd/COM5501_0/MAC_TX_DATA[34]} {bd/COM5501_0/MAC_TX_DATA[35]} {bd/COM5501_0/MAC_TX_DATA[36]} {bd/COM5501_0/MAC_TX_DATA[37]} {bd/COM5501_0/MAC_TX_DATA[38]} {bd/COM5501_0/MAC_TX_DATA[39]} {bd/COM5501_0/MAC_TX_DATA[40]} {bd/COM5501_0/MAC_TX_DATA[41]} {bd/COM5501_0/MAC_TX_DATA[42]} {bd/COM5501_0/MAC_TX_DATA[43]} {bd/COM5501_0/MAC_TX_DATA[44]} {bd/COM5501_0/MAC_TX_DATA[45]} {bd/COM5501_0/MAC_TX_DATA[46]} {bd/COM5501_0/MAC_TX_DATA[47]} {bd/COM5501_0/MAC_TX_DATA[48]} {bd/COM5501_0/MAC_TX_DATA[49]} {bd/COM5501_0/MAC_TX_DATA[50]} {bd/COM5501_0/MAC_TX_DATA[51]} {bd/COM5501_0/MAC_TX_DATA[52]} {bd/COM5501_0/MAC_TX_DATA[53]} {bd/COM5501_0/MAC_TX_DATA[54]} {bd/COM5501_0/MAC_TX_DATA[55]} {bd/COM5501_0/MAC_TX_DATA[56]} {bd/COM5501_0/MAC_TX_DATA[57]} {bd/COM5501_0/MAC_TX_DATA[58]} {bd/COM5501_0/MAC_TX_DATA[59]} {bd/COM5501_0/MAC_TX_DATA[60]} {bd/COM5501_0/MAC_TX_DATA[61]} {bd/COM5501_0/MAC_TX_DATA[62]} {bd/COM5501_0/MAC_TX_DATA[63]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 8 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {bd/COM5501_0/MAC_TX_DATA_VALID[0]} {bd/COM5501_0/MAC_TX_DATA_VALID[1]} {bd/COM5501_0/MAC_TX_DATA_VALID[2]} {bd/COM5501_0/MAC_TX_DATA_VALID[3]} {bd/COM5501_0/MAC_TX_DATA_VALID[4]} {bd/COM5501_0/MAC_TX_DATA_VALID[5]} {bd/COM5501_0/MAC_TX_DATA_VALID[6]} {bd/COM5501_0/MAC_TX_DATA_VALID[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 64 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {bd/tcp_udp_client_0/mac_tx_data[0]} {bd/tcp_udp_client_0/mac_tx_data[1]} {bd/tcp_udp_client_0/mac_tx_data[2]} {bd/tcp_udp_client_0/mac_tx_data[3]} {bd/tcp_udp_client_0/mac_tx_data[4]} {bd/tcp_udp_client_0/mac_tx_data[5]} {bd/tcp_udp_client_0/mac_tx_data[6]} {bd/tcp_udp_client_0/mac_tx_data[7]} {bd/tcp_udp_client_0/mac_tx_data[8]} {bd/tcp_udp_client_0/mac_tx_data[9]} {bd/tcp_udp_client_0/mac_tx_data[10]} {bd/tcp_udp_client_0/mac_tx_data[11]} {bd/tcp_udp_client_0/mac_tx_data[12]} {bd/tcp_udp_client_0/mac_tx_data[13]} {bd/tcp_udp_client_0/mac_tx_data[14]} {bd/tcp_udp_client_0/mac_tx_data[15]} {bd/tcp_udp_client_0/mac_tx_data[16]} {bd/tcp_udp_client_0/mac_tx_data[17]} {bd/tcp_udp_client_0/mac_tx_data[18]} {bd/tcp_udp_client_0/mac_tx_data[19]} {bd/tcp_udp_client_0/mac_tx_data[20]} {bd/tcp_udp_client_0/mac_tx_data[21]} {bd/tcp_udp_client_0/mac_tx_data[22]} {bd/tcp_udp_client_0/mac_tx_data[23]} {bd/tcp_udp_client_0/mac_tx_data[24]} {bd/tcp_udp_client_0/mac_tx_data[25]} {bd/tcp_udp_client_0/mac_tx_data[26]} {bd/tcp_udp_client_0/mac_tx_data[27]} {bd/tcp_udp_client_0/mac_tx_data[28]} {bd/tcp_udp_client_0/mac_tx_data[29]} {bd/tcp_udp_client_0/mac_tx_data[30]} {bd/tcp_udp_client_0/mac_tx_data[31]} {bd/tcp_udp_client_0/mac_tx_data[32]} {bd/tcp_udp_client_0/mac_tx_data[33]} {bd/tcp_udp_client_0/mac_tx_data[34]} {bd/tcp_udp_client_0/mac_tx_data[35]} {bd/tcp_udp_client_0/mac_tx_data[36]} {bd/tcp_udp_client_0/mac_tx_data[37]} {bd/tcp_udp_client_0/mac_tx_data[38]} {bd/tcp_udp_client_0/mac_tx_data[39]} {bd/tcp_udp_client_0/mac_tx_data[40]} {bd/tcp_udp_client_0/mac_tx_data[41]} {bd/tcp_udp_client_0/mac_tx_data[42]} {bd/tcp_udp_client_0/mac_tx_data[43]} {bd/tcp_udp_client_0/mac_tx_data[44]} {bd/tcp_udp_client_0/mac_tx_data[45]} {bd/tcp_udp_client_0/mac_tx_data[46]} {bd/tcp_udp_client_0/mac_tx_data[47]} {bd/tcp_udp_client_0/mac_tx_data[48]} {bd/tcp_udp_client_0/mac_tx_data[49]} {bd/tcp_udp_client_0/mac_tx_data[50]} {bd/tcp_udp_client_0/mac_tx_data[51]} {bd/tcp_udp_client_0/mac_tx_data[52]} {bd/tcp_udp_client_0/mac_tx_data[53]} {bd/tcp_udp_client_0/mac_tx_data[54]} {bd/tcp_udp_client_0/mac_tx_data[55]} {bd/tcp_udp_client_0/mac_tx_data[56]} {bd/tcp_udp_client_0/mac_tx_data[57]} {bd/tcp_udp_client_0/mac_tx_data[58]} {bd/tcp_udp_client_0/mac_tx_data[59]} {bd/tcp_udp_client_0/mac_tx_data[60]} {bd/tcp_udp_client_0/mac_tx_data[61]} {bd/tcp_udp_client_0/mac_tx_data[62]} {bd/tcp_udp_client_0/mac_tx_data[63]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 64 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list {bd/tcp_udp_client_0/mac_rx_data[0]} {bd/tcp_udp_client_0/mac_rx_data[1]} {bd/tcp_udp_client_0/mac_rx_data[2]} {bd/tcp_udp_client_0/mac_rx_data[3]} {bd/tcp_udp_client_0/mac_rx_data[4]} {bd/tcp_udp_client_0/mac_rx_data[5]} {bd/tcp_udp_client_0/mac_rx_data[6]} {bd/tcp_udp_client_0/mac_rx_data[7]} {bd/tcp_udp_client_0/mac_rx_data[8]} {bd/tcp_udp_client_0/mac_rx_data[9]} {bd/tcp_udp_client_0/mac_rx_data[10]} {bd/tcp_udp_client_0/mac_rx_data[11]} {bd/tcp_udp_client_0/mac_rx_data[12]} {bd/tcp_udp_client_0/mac_rx_data[13]} {bd/tcp_udp_client_0/mac_rx_data[14]} {bd/tcp_udp_client_0/mac_rx_data[15]} {bd/tcp_udp_client_0/mac_rx_data[16]} {bd/tcp_udp_client_0/mac_rx_data[17]} {bd/tcp_udp_client_0/mac_rx_data[18]} {bd/tcp_udp_client_0/mac_rx_data[19]} {bd/tcp_udp_client_0/mac_rx_data[20]} {bd/tcp_udp_client_0/mac_rx_data[21]} {bd/tcp_udp_client_0/mac_rx_data[22]} {bd/tcp_udp_client_0/mac_rx_data[23]} {bd/tcp_udp_client_0/mac_rx_data[24]} {bd/tcp_udp_client_0/mac_rx_data[25]} {bd/tcp_udp_client_0/mac_rx_data[26]} {bd/tcp_udp_client_0/mac_rx_data[27]} {bd/tcp_udp_client_0/mac_rx_data[28]} {bd/tcp_udp_client_0/mac_rx_data[29]} {bd/tcp_udp_client_0/mac_rx_data[30]} {bd/tcp_udp_client_0/mac_rx_data[31]} {bd/tcp_udp_client_0/mac_rx_data[32]} {bd/tcp_udp_client_0/mac_rx_data[33]} {bd/tcp_udp_client_0/mac_rx_data[34]} {bd/tcp_udp_client_0/mac_rx_data[35]} {bd/tcp_udp_client_0/mac_rx_data[36]} {bd/tcp_udp_client_0/mac_rx_data[37]} {bd/tcp_udp_client_0/mac_rx_data[38]} {bd/tcp_udp_client_0/mac_rx_data[39]} {bd/tcp_udp_client_0/mac_rx_data[40]} {bd/tcp_udp_client_0/mac_rx_data[41]} {bd/tcp_udp_client_0/mac_rx_data[42]} {bd/tcp_udp_client_0/mac_rx_data[43]} {bd/tcp_udp_client_0/mac_rx_data[44]} {bd/tcp_udp_client_0/mac_rx_data[45]} {bd/tcp_udp_client_0/mac_rx_data[46]} {bd/tcp_udp_client_0/mac_rx_data[47]} {bd/tcp_udp_client_0/mac_rx_data[48]} {bd/tcp_udp_client_0/mac_rx_data[49]} {bd/tcp_udp_client_0/mac_rx_data[50]} {bd/tcp_udp_client_0/mac_rx_data[51]} {bd/tcp_udp_client_0/mac_rx_data[52]} {bd/tcp_udp_client_0/mac_rx_data[53]} {bd/tcp_udp_client_0/mac_rx_data[54]} {bd/tcp_udp_client_0/mac_rx_data[55]} {bd/tcp_udp_client_0/mac_rx_data[56]} {bd/tcp_udp_client_0/mac_rx_data[57]} {bd/tcp_udp_client_0/mac_rx_data[58]} {bd/tcp_udp_client_0/mac_rx_data[59]} {bd/tcp_udp_client_0/mac_rx_data[60]} {bd/tcp_udp_client_0/mac_rx_data[61]} {bd/tcp_udp_client_0/mac_rx_data[62]} {bd/tcp_udp_client_0/mac_rx_data[63]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 8 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list {bd/tcp_udp_client_0/mac_rx_data_valid[0]} {bd/tcp_udp_client_0/mac_rx_data_valid[1]} {bd/tcp_udp_client_0/mac_rx_data_valid[2]} {bd/tcp_udp_client_0/mac_rx_data_valid[3]} {bd/tcp_udp_client_0/mac_rx_data_valid[4]} {bd/tcp_udp_client_0/mac_rx_data_valid[5]} {bd/tcp_udp_client_0/mac_rx_data_valid[6]} {bd/tcp_udp_client_0/mac_rx_data_valid[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 8 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list {bd/tcp_udp_client_0/mac_tx_data_valid[0]} {bd/tcp_udp_client_0/mac_tx_data_valid[1]} {bd/tcp_udp_client_0/mac_tx_data_valid[2]} {bd/tcp_udp_client_0/mac_tx_data_valid[3]} {bd/tcp_udp_client_0/mac_tx_data_valid[4]} {bd/tcp_udp_client_0/mac_tx_data_valid[5]} {bd/tcp_udp_client_0/mac_tx_data_valid[6]} {bd/tcp_udp_client_0/mac_tx_data_valid[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list bd/tcp_udp_client_0/mac_rx_eof]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list bd/COM5501_0/MAC_RX_EOF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property port_width 1 [get_debug_ports u_ila_1/probe10]
connect_debug_port u_ila_1/probe10 [get_nets [list bd/tcp_udp_client_0/mac_rx_frame_valid]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe11]
set_property port_width 1 [get_debug_ports u_ila_1/probe11]
connect_debug_port u_ila_1/probe11 [get_nets [list bd/COM5501_0/MAC_RX_FRAME_VALID]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe12]
set_property port_width 1 [get_debug_ports u_ila_1/probe12]
connect_debug_port u_ila_1/probe12 [get_nets [list bd/tcp_udp_client_0/mac_rx_sof]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe13]
set_property port_width 1 [get_debug_ports u_ila_1/probe13]
connect_debug_port u_ila_1/probe13 [get_nets [list bd/COM5501_0/MAC_RX_SOF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe14]
set_property port_width 1 [get_debug_ports u_ila_1/probe14]
connect_debug_port u_ila_1/probe14 [get_nets [list bd/COM5501_0/MAC_TX_CTS]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe15]
set_property port_width 1 [get_debug_ports u_ila_1/probe15]
connect_debug_port u_ila_1/probe15 [get_nets [list bd/tcp_udp_client_0/mac_tx_cts]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe16]
set_property port_width 1 [get_debug_ports u_ila_1/probe16]
connect_debug_port u_ila_1/probe16 [get_nets [list bd/COM5501_0/MAC_TX_EOF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe17]
set_property port_width 1 [get_debug_ports u_ila_1/probe17]
connect_debug_port u_ila_1/probe17 [get_nets [list bd/tcp_udp_client_0/mac_tx_eof]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe18]
set_property port_width 1 [get_debug_ports u_ila_1/probe18]
connect_debug_port u_ila_1/probe18 [get_nets [list bd/COM5501_0/RESET_N]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe19]
set_property port_width 1 [get_debug_ports u_ila_1/probe19]
connect_debug_port u_ila_1/probe19 [get_nets [list bd/COM5501_0/SYNC_RESET]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe20]
set_property port_width 1 [get_debug_ports u_ila_1/probe20]
connect_debug_port u_ila_1/probe20 [get_nets [list bd/tcp_udp_client_0/sync_reset]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_MGT_B228_RX0_N]
